
























































100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 58465/58465 [01:55<00:00, 507.45it/s]



















100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 19584/19584 [00:37<00:00, 518.33it/s]











100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13418/13418 [00:25<00:00, 519.86it/s]
Traceback (most recent call last):
  File "train_retacred_datamap.py", line 237, in <module>
    main()
  File "train_retacred_datamap.py", line 220, in main
    challenge_test_features = processor.read(challenge_test_file)
  File "/nethome/mrungta8/project/ProjectPURE/Mukund/RE_improved_baseline/prepro_datamap.py", line 173, in read
    with open(file_in, "r") as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/retacred/challenge_set.json'
Traceback (most recent call last):
  File "train_retacred_datamap.py", line 237, in <module>
    main()
  File "train_retacred_datamap.py", line 220, in main
    challenge_test_features = processor.read(challenge_test_file)
  File "/nethome/mrungta8/project/ProjectPURE/Mukund/RE_improved_baseline/prepro_datamap.py", line 173, in read
    with open(file_in, "r") as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/retacred/challenge_set.json'