


















































































































































100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 120352/120352 [04:56<00:00, 406.05it/s]



























100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22631/22631 [00:55<00:00, 406.62it/s]


















100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15509/15509 [00:38<00:00, 399.73it/s]
Traceback (most recent call last):
  File "train_tacred_datamap.py", line 237, in <module>
    main()
  File "train_tacred_datamap.py", line 220, in main
    challenge_test_features = processor.read(challenge_test_file)
  File "/nethome/mrungta8/project/ProjectPURE/Mukund/RE_improved_baseline/prepro_datamap.py", line 141, in read
    with open(file_in, "r") as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/tacred_extend/challenge_set.json'
Traceback (most recent call last):
  File "train_tacred_datamap.py", line 237, in <module>
    main()
  File "train_tacred_datamap.py", line 220, in main
    challenge_test_features = processor.read(challenge_test_file)
  File "/nethome/mrungta8/project/ProjectPURE/Mukund/RE_improved_baseline/prepro_datamap.py", line 141, in read
    with open(file_in, "r") as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/tacred_extend/challenge_set.json'